markdown: rdiscount
permalink: /:title/
url: http://hitwangyu.net
name: hitwangyu.NET
author: hitwangyu
qq: 356977819
email: p787806@gmail.com
duoshuo: hitwangyu
github: hitwangyu
pygments: true
safe: true
paginate: 20
about: "这里是 hitwangyu 的个人博客，创建于 2014 年 3 月末。之前找工作期间在CSDN整了一小段时间。<br /><br />今天终于狠下决心进入主流社会，开始下决心学点东西了...欢迎批评指正..."
